# Generated by Django 3.0.4 on 2020-03-18 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vending_machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_area', models.CharField(max_length=30)),
                ('machine_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_quantity', models.IntegerField()),
                ('vending_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending_machine.Vending_machine')),
            ],
        ),
    ]
