# Generated by Django 3.0.4 on 2020-03-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transsactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_products', models.CharField(choices=[('5', '5'), ('10', '10'), ('20', '20'), ('50', '50'), ('100', '100'), ('500', '500'), ('1000', '1000')], max_length=30)),
                ('available_products', models.ManyToManyField(to='vending_machine.Products')),
            ],
        ),
    ]
