# Generated by Django 3.0.4 on 2020-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine', '0003_auto_20200318_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='per_unit_price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='transsactions',
            name='available_products',
            field=models.ManyToManyField(to='vending_machine.Products'),
        ),
    ]
